//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Field
{
    public Field NextField { get; set; }

    public FieldType Type { get; set; }

    public Piece Piece { get; set; }


    public Field()
    {
        Type = FieldType.Normal;
    }

    
 
    public virtual void PlacePiece(Piece piece)
    {
        piece.Field.Piece = null;
        piece.Field = this;
        this.Piece = piece;
    }
}

