//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
    public Board Board { get; set; }


    public void Next()
    {
        PlayerWhite.TakeTurn();

    }

    public Game()
    {
        Board = new Board();
        PlayerBlack = new Player(Board.StartBlack);
        PlayerWhite = new Player(Board.StartWhite);

    }
	public Player PlayerBlack
	{
		get;
		set;
	}

	public Player PlayerWhite
	{
		get;
		set;
	}

}

