//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
    public List<Piece> Pieces { get; set; }

    private Field _startField;

    private Random _r;


    public Player(Field startField)
    {
        this._startField = startField;
        Pieces = new List<Piece>();
        Pieces.Add(new Piece()
        {
            Field = startField
        });
        _r = new Random();
    }

    internal void TakeTurn()
    {
        int diceThrow = _r.Next(0, 4);
        Piece piece = Pieces.FirstOrDefault();

        Field thefield = piece.Field;

        for (int i = 0; i < diceThrow; i++)
        {
            thefield = thefield.NextField;
        }

        thefield.PlacePiece(piece);


        Console.WriteLine("piece moved " + diceThrow + " places");

    }
}

